src/Entity/Regime.php
<?php

namespace App\Entity;

use App\Repository\RegimeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RegimeRepository::class)]
class Regime
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $discription = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dDate = null;

    #[ORM\Column]
    private ?int $nb_calorie = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $duree = null;
    
    //#[ORM\OneToMany(mappedBy: 'regime', targetEntity: Composition::class)]
    //private Collection $compositions;
    
    
    #[ORM\Column(length: 255)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDiscription(): ?string
    {
        return $this->discription;
    }


    public function setDiscription(string $discription): self
    {
        $this->discription = $discription;

        return $this;
    }

    public function getDDate(): ?\DateTimeInterface
    {
        return $this->dDate;
    }

    public function setDDate(\DateTimeInterface $dDate): self
    {
        $this->dDate = $dDate;

        return $this;
    }

    public function getNbCalorie(): ?int
    {
        return $this->nb_calorie;
    }

    public function setNbCalorie(int $nb_calorie): self
    {
        $this->nb_calorie = $nb_calorie;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

}

src/Form/RegimeType.php
<?php

namespace App\Form;

use App\Entity\Regime;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class RegimeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('discription')
            ->add('dDate')
            ->add('nb_calorie')
            ->add('duree')
            ->add('image',FileType::class, [
                'data_class' => null,
                'label' => false,
                'required'  => false
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Regime::class,
        ]);
    }
}

src/Controller/RegimeController.php
<?php

namespace App\Controller;

use App\Entity\Regime;
use App\Form\RegimeType;
use App\Repository\RegimeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

#[Route('/regime')]
class RegimeController extends AbstractController
{
    #[Route('/', name: 'app_regime_index', methods: ['GET'])]
    public function index(RegimeRepository $regimeRepository): Response
    {
        return $this->render('regime/index.html.twig', [
            'regimes' => $regimeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_regime_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RegimeRepository $regimeRepository): Response
    {
        $regime = new Regime();
        $form = $this->createForm(RegimeType::class, $regime);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            if ($image) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $newFilename = $originalFilename.'-'.uniqid().'.'.$image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $regime->setimage($newFilename);
            }
            $regimeRepository->save($regime, true);

            return $this->redirectToRoute('app_regime_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('regime/new.html.twig', [
            'regime' => $regime,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_regime_show', methods: ['GET'])]
    public function show(Regime $regime): Response
    {
        return $this->render('regime/show.html.twig', [
            'regime' => $regime,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_regime_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Regime $regime, RegimeRepository $regimeRepository): Response
    {
        $form = $this->createForm(RegimeType::class, $regime);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $regimeRepository->save($regime, true);

            return $this->redirectToRoute('app_regime_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('regime/edit.html.twig', [
            'regime' => $regime,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_regime_delete', methods: ['POST'])]
    public function delete(Request $request, Regime $regime, RegimeRepository $regimeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$regime->getId(), $request->request->get('_token'))) {
            $regimeRepository->remove($regime, true);
        }

        return $this->redirectToRoute('app_regime_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/regime/_delete_form.html.twig
<form method="post" action="{{ path('app_regime_delete', {'id': regime.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ regime.id) }}">
    <button class="btn">Delete</button>
</form>

templates/regime/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/regime/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Regime{% endblock %}

{% block body %}
    <h1>Edit Regime</h1>

    {{ include('regime/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_regime_index') }}">back to list</a>

    {{ include('regime/_delete_form.html.twig') }}
{% endblock %}

templates/regime/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Regime index{% endblock %}

{% block body %}
    <h1>Regime index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Discription</th>
                <th>DDate</th>
                <th>Nb_calorie</th>
                <th>Duree</th>
                <th>image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for regime in regimes %}
            <tr>
                <td>{{ regime.id }}</td>
                <td>{{ regime.name }}</td>
                <td>{{ regime.discription }}</td>
                <td>{{ regime.dDate ? regime.dDate|date('Y-m-d') : '' }}</td>
                <td>{{ regime.nbCalorie }}</td>
                
                <td>{{ regime.duree ? regime.duree|date('H:i:s') : '' }}</td>
                
                <td>{% if regime.image %}
					<img src="/uploads/{{regime.image}}" alt="">
					{% endif %}</td>
                <td>
                    <a href="{{ path('app_regime_show', {'id': regime.id}) }}">show</a>
                    <a href="{{ path('app_regime_edit', {'id': regime.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_regime_new') }}">Create new</a>
{% endblock %}

templates/regime/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Regime{% endblock %}

{% block body %}
    <h1>Create new Regime</h1>

    {{ include('regime/_form.html.twig') }}

    <a href="{{ path('app_regime_index') }}">back to list</a>
{% endblock %}

templates/regime/show.html.twig
{% extends 'back_.html.twig' %}

{% block title %}Regime{% endblock %}

{% block body %}
    <h1>Regime</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ regime.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ regime.name }}</td>
            </tr>
            <tr>
                <th>Discription</th>
                <td>{{ regime.discription }}</td>
            </tr>
            <tr>
                <th>DDate</th>
                <td>{{ regime.dDate ? regime.dDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nb_calorie</th>
                <td>{{ regime.nbCalorie }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ regime.duree ? regime.duree|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>
    

    <a href="{{ path('app_regime_index') }}">back to list</a>

    <a href="{{ path('app_regime_edit', {'id': regime.id}) }}">edit</a>

    {{ include('regime/_delete_form.html.twig') }}
{% endblock %}